### ISSUE TITLE
Unexpected status code : 500

### ISSUE THREAD

**Issue by stijnvanrenterghem** [lawrensylvan/immoweb-keeper#7]
Error while processing immoweb code 9496361 !
....(node:3172) UnhandledPromiseRejectionWarning: Unexpected status code : 500
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3172) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3172) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

...........Error while processing immoweb code 9495012 !
(node:19700) UnhandledPromiseRejectionWarning: Unexpected status code : 500
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19700) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19700) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lawrensylvan** [comment]
Hello Stijn,
Indeed, the code seemed to stop working a few weeks ago (before that, it was working like a charm) and I didn't have time to investigate. My issue was some unauthorized status when trying to perform the GET requests, as if somehow Immoweb added some extra security (which is surprising because it's supposed to be the same GET request that would be sent by the web browser when browsing Immoweb yourself).
But here you have a 500 error suggesting an exception in the Immoweb backend itself.

Now that I know that this project could be of interest for some people, I will try to reproduce and investigate this issue and I'll let you know.
Thanks for your interest.

**Comment by stijnvanrenterghem** [comment]
Hi Laurent,

I have no problems with the application, expect the 500 error.
If the ID gives errors, the item can be skipped. The problem is that other items are not processed anymore.

Thanks for sharing this nice project.

**Comment by lawrensylvan** [comment]
Hi Stijn,

I have fixed a bug (the request was not following always following HTTP redirections). I changed the fetching library that I use for that so maybe it will have solved your problem at the same time. Could you try ?

**Comment by stijnvanrenterghem** [comment]
Hi Laurent,

Thank you to look at the bug.
It seems to work better. I only had an error one time.

............fs.js:177
    throw new ERR_INVALID_CALLBACK(cb);
    ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at makeCallback (fs.js:177:11)
    at Object.unlink (fs.js:1240:14)
    at RedirectableRequest.<anonymous> (\server\routine\routine.js:244:16)
    at RedirectableRequest.emit (events.js:375:28)
    at ClientRequest.eventHandlers.<computed> (\server\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (events.js:375:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:375:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3) {
  code: 'ERR_INVALID_CALLBACK'
}
