### ISSUE TITLE
'tee' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by jrvhulle** [lawrensylvan/immoweb-keeper#9]
Hi,

When executing the npm run routine command, I am getting the 'tee' is not recognized as an internal or external command, operable program or batch file. I am attaching screenshot below for reference.
![error](https://user-images.githubusercontent.com/49834959/142942914-7bd82001-bb3e-457e-a6df-b98292a08040.JPG)

**Comment by lawrensylvan** [comment]
Hi,

Indeed, I am using this utility command tee which helps for formatting logs, but I see it is not compatible with Windows cmd line. I will make sure to adapt the project so that it runs smoothly on all OSes. In the meantime, I suggest you run the command with Windows Powersheel instead of cmd, I heard it should know about the tee command.

If that does not work, you can run the routine differently by doing "node server/routine/src/routine.js". You will just miss the output being redirected to a log file, which is not a big deal.

**Comment by jrvhulle** [comment]
Hi,

Thanks for the suggestions but neither work for me :/
Tried in Windows Powershell, the same error appears:
![image](https://user-images.githubusercontent.com/49834959/143688491-e9becd4d-4cf4-43ce-a6a3-b305f732d0b1.png)

Tried with the command "node server/routine/src/routine.js" & then I get the Error: Cannot find module 'lodash':
![image](https://user-images.githubusercontent.com/49834959/143688517-95adf61b-0abc-4058-8c3d-5e7d7bb8d875.png)

Do you have other suggestions or should I just wait until you adapt the project?

Thanks!

**Comment by alex6H** [comment]
Hi,

Here you'll find the solution for tee on windows : 
Download this [https://github.com/tebelorg/Tump/releases/download/v1.0.0/TagUI_Windows.zip](url) 
Go to  tagui\src\unx folder and copy the tee.exe to C:\Windows\System32\
Solution comes from [https://github.com/kelaberetiv/TagUI/issues/450](url)

Other possible errors: 
On your print screen I see Error: Cannot find module 'lodash'
I think you have to install all dependencies manually. I had the same problem and had to run : npm install lodash --save
Do it for every missing package.

in routine.js line 9 : 
**const MongoClient = require('mongodb');** need to be replaced by **const MongoClient = require('mongodb').MongoClient;**

I had these problems when trying to run the script.

Alex

**Comment by jrvhulle** [comment]
Hi Alex,

Thanks a lot for the help! I did everything you said and it already helped a lot.
However, there is another error with regard to config.json that I cannot fix:
![image](https://user-images.githubusercontent.com/49834959/148046907-b6f7ef79-8b98-4377-b957-fa5d5b7d56b0.png)

Can you help me to fix this as well?

Thanks!

**Comment by alex6H** [comment]
Hi Jef,

According to your screenshot the config.json is missing. Follow what lawrensylvan explained in the [github](https://github.com/lawrensylvan/immoweb-keeper) under "Setup config"

![image](https://user-images.githubusercontent.com/48403935/148111637-292f1a4c-e77a-479b-81ef-3a8083803e9b.png)

Put the config.json in your folder under  "~immoweb-keeper-master\server" and run the routine job.

Let me know if it solves your issue.

Alex

**Comment by jrvhulle** [comment]
Hi Alex,

I already had this config.json file and it still didn't work. But after I reinstalled everything from the start, it did.
So I finally managed to get some data in my Mongodb database!

Thanks for all the help on this!
